const Properties = [
  {
    id: '1',
    status: 'available',
    price: '300000.00',
    state: 'lagos',
    city: 'ikeja',
    address: 'computer village',
    type: '2 bedroom',
    created_on: new Date(),
    image_url: 'https://images.com/img/myimage.png',
    ownerEmail: 'owner1@email.com',
    ownerPhoneNumber: '08033233333',
  },
  {
    id: '2',
    status: 'available',
    price: '300000.00',
    state: 'lagos',
    city: 'ikeja',
    address: 'computer village',
    type: '2 bedroom',
    created_on: new Date(),
    image_url: 'https://images.com/img/myimage.png',
    ownerEmail: 'owner2@email.com',
    ownerPhoneNumber: '08033233433',
  },
  {
    id: '3',
    status: 'available',
    price: '300000.00',
    state: 'lagos',
    city: 'ikeja',
    address: 'computer village',
    type: '2 bedroom',
    created_on: new Date(),
    image_url: 'https://images.com/img/myimage.png',
    ownerEmail: 'owner3@email.com',
    ownerPhoneNumber: '08033235333',
  },
  {
    id: '4',
    status: 'available',
    price: '300000.00',
    state: 'lagos',
    city: 'ikeja',
    address: 'computer village',
    type: '2 bedroom',
    created_on: new Date(),
    image_url: 'https://images.com/img/myimage.png',
    ownerEmail: 'owner4@email.com',
    ownerPhoneNumber: '08033933333',
  },
];

export default Properties;
