const Properties = [
  {
    id: 1,
    owner: 1,
    status: 'available',
    price: 300000.00,
    state: 'lagos',
    city: 'ikeja',
    address: 'computer village',
    type: '2 bedroom',
    created_on: new Date(),
    image_url: 'https://images.com/img/myimage.png',
  },
  {
    id: 2,
    owner: 1,
    status: 'available',
    price: 300000.00,
    state: 'lagos',
    city: 'ikeja',
    address: 'computer village',
    type: '2 bedroom',
    created_on: new Date(),
    image_url: 'https://images.com/img/myimage.png',
  },
  {
    id: 3,
    owner: 1,
    status: 'available',
    price: 300000.00,
    state: 'lagos',
    city: 'ikeja',
    address: 'computer village',
    type: '2 bedroom',
    created_on: new Date(),
    image_url: 'https://images.com/img/myimage.png',
  },
  {
    id: 4,
    owner: 1,
    status: 'available',
    price: 300000.00,
    state: 'lagos',
    city: 'ikeja',
    address: 'computer village',
    type: '2 bedroom',
    created_on: new Date(),
    image_url: 'https://images.com/img/myimage.png',
  },
];

export default Properties;
